language: cpp

matrix:
  include:
  - os: linux
    env: ARCH=x86_64
    compiler: gcc
    sudo: require
    dist: trusty
  - os: linux
    env: ARCH=i386
    compiler: gcc
    sudo: require
    dist: trusty
  - os: osx

before_install:
  - bash ./.travis/before_install.sh

install:
  - bash ./.travis/install.sh

script:
  - bash ./.travis/script.sh

after_success:
  - bash ./.travis/after_success.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
