version: "{build}"
branches:
  only:
  - master
image: Visual Studio 2015
environment:
  TRAVIS_REPO_SLUG: olive-editor/olive
matrix:
- MSYSTEM: MINGW64
 ARCH: x86_64
 NSISDEF: -DX64
- MSYSTEM: MINGW32
 ARCH: i686
build_script:
- cmd: appveyor-build.bat
artifacts:
- path: Olive*.zip
  name: Olive Portable
- path: Olive*.exe
  name: Olive Installer
