version: "{build}"
branches:
  only:
  - master
image: Visual Studio 2015
environment:
  TRAVIS_REPO_SLUG: olive-editor/olive
build_script:
- cmd: appveyor-build.bat
artifacts:
- path: Olive*.zip
  name: Olive Portable
- path: Olive*.exe
  name: Olive Installer
